library(tidyverse)

cereal <- tribble(
  ~store,            ~cereal,            ~year, 
  "cereal_outlet",   "bran_flakes",      2010,     
  "cereal_outlet",   "count_chocula",    2010,  
  "cereal_outlet",   "fruit_loops",      2010, 
  "cereal_outlet",   "rice_krispies",    2010, 
  "cereal_outlet",   "trix",             2010,
  "ce_mart",         "bran_flakes",      2010,
  "ce_mart",         "count_chocula",    2010,
  "ce_mart",         "fruit_loops",      2010,
  "ce_mart",         "rice_krispies",    2010,
  "ce_mart",         "trix",             2010,
  "cer_ya",          "bran_flakes",      2010,
  "cer_ya",          "count_chocula",    2010,
  "cer_ya",          "fruit_loops",      2010,
  "cer_ya",          "rice_krispies",    2010,
  "cer_ya",          "trix",             2010,
  "cereal_outlet",   "bran_flakes",      2012, 
  "cereal_outlet",   "count_chocula",    2012, 
  "cereal_outlet",   "fruit_loops",      2012, 
  "cereal_outlet",   "rice_krispies",    2012, 
  "cereal_outlet",   "trix",             2012, 
  "ce_mart",         "bran_flakes",      2012, 
  "ce_mart",         "count_chocula",    2012, 
  "ce_mart",         "fruit_loops",      2012, 
  "ce_mart",         "rice_krispies",    2012, 
  "ce_mart",         "trix",             2012, 
  "cer_ya",          "bran_flakes",      2012, 
  "cer_ya",          "count_chocula",    2012, 
  "cer_ya",          "fruit_loops",      2012, 
  "cer_ya",          "rice_krispies",    2012, 
  "cer_ya",          "trix",             2012, 
  "cereal_outlet",   "bran_flakes",      2015, 
  "cereal_outlet",   "count_chocula",    2015, 
  "cereal_outlet",   "fruit_loops",      2015, 
  "cereal_outlet",   "rice_krispies",    2015, 
  "cereal_outlet",   "trix",             2015, 
  "ce_mart",         "bran_flakes",      2015, 
  "ce_mart",         "count_chocula",    2015, 
  "ce_mart",         "fruit_loops",      2015, 
  "ce_mart",         "rice_krispies",    2015, 
  "ce_mart",         "trix",             2015, 
  "cer_ya",          "bran_flakes",      2015, 
  "cer_ya",          "count_chocula",    2015, 
  "cer_ya",          "fruit_loops",      2015, 
  "cer_ya",          "rice_krispies",    2015, 
  "cer_ya",          "trix",             2015, 
  "cereal_outlet",   "bran_flakes",      2021, 
  "cereal_outlet",   "count_chocula",    2021, 
  "cereal_outlet",   "fruit_loops",      2021, 
  "cereal_outlet",   "rice_krispies",    2021, 
  "cereal_outlet",   "trix",             2021, 
  "ce_mart",         "bran_flakes",      2021, 
  "ce_mart",         "count_chocula",    2021, 
  "ce_mart",         "fruit_loops",      2021, 
  "ce_mart",         "rice_krispies",    2021, 
  "ce_mart",         "trix",             2021, 
  "cer_ya",          "bran_flakes",      2021, 
  "cer_ya",          "count_chocula",    2021, 
  "cer_ya",          "fruit_loops",      2021, 
  "cer_ya",          "rice_krispies",    2021, 
  "cer_ya",          "trix",             2021, 
) %>% 
  mutate(price_usd = runif(60, min = 3, max = 6),
         cereal_title = case_when(
           cereal == "bran_flakes" ~ "Bran Flakes",
           cereal == "count_chocula" ~ "Count Chocula",
           cereal == "fruit_loops" ~ "Fruit Loops", 
           cereal == "rice_krispies" ~ "Rice Krispies",
           cereal == "trix" ~ "Trix"
         ),
         store_title = case_when(
           store == "cereal_outlet" ~ "Cereal Outlet",
           store == "ce_mart" ~ "Ce-Mart",
           store == "cer_ya" ~ "Cer-ya"
         ))
